name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: pioneer_converter
            asset_name: pioneer_converter-linux-amd64
          - os: windows-latest
            artifact_name: pioneer_converter.exe
            asset_name: pioneer_converter-windows-amd64.exe

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Build Release
        run: cargo build --release

      - name: Package Assets (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          mkdir dist
          cp target/release/${{ matrix.artifact_name }} dist/
          cp LICENSE-FOUL dist/
          cd dist && tar -czvf ../${{ matrix.asset_name }}.tar.gz *

      - name: Package Assets (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          mkdir dist
          copy target\release\${{ matrix.artifact_name }} dist\
          copy LICENSE-FOUL dist\
          powershell Compress-Archive -Path dist\* -DestinationPath ${{ matrix.asset_name }}.zip

      - name: Upload to Release
        uses: softprops/action-gh-release@v3
        with:
          files: |
            *.tar.gz
            *.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
